kordat <- read.table("variants1.txt",sep='\t', dec=',', row.names=1, header=TRUE, strip.white = T, stringsAsFactors = T)
kordat[9:ncol(kordat)] <- lapply(kordat[9:ncol(kordat)], as.factor)
sink("results.txt")
print(as.data.frame.matrix(summary(kordat))[9:ncol(kordat)])
sl.by.b <- split(kordat$Slope, kordat$b)
print(sl.by.b)
kordat$Average <- apply(kordat[c("Slope","Intercept","adj.r.squared")],1,mean)
print(sapply(kordat[1:8], function(x) tapply(x, kordat$f, sd)))
print(kordat$adj.r.squared > -0.3)
prockordat <- kordat[kordat$adj.r.squared > -0.3,]
prockordat$Slope <- sapply(prockordat$Slope, function(k) {1-1/k})
print(prockordat)
svg("scatter.svg")
plot(kordat$MAD, kordat$Average)
dev.off()
library(RColorBrewer)
svg("boxplot.svg")
boxplot(as.data.frame(split(kordat$Intercept,kordat$f)), col = brewer.pal(n = length(levels(kordat$f)), name = "Set3"))
dev.off()
